backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)

media_folder: static/img
public_folder: /img

collections:
  - label: 'General'
    name: 'General'
    files:
      - label: 'Config ⚙️'
        name: 'config'
        file: 'content/config.md'
        fields:
          - {label: 'Name', name: 'name', widget: string}
          - {label: 'Title', name: 'title', widget: string}
          - {label: 'Email', name: 'email', widget: string}
          - label: Social
            name: social
            widget: object
            fields:
              - {label: 'Github', name: 'github', widget: string}
              - {label: 'Instagram', name: 'instagram', widget: string}
              - {label: 'Linkedin', name: 'linkedin', widget: string}
              - {label: 'Twitter', name: 'twitter', widget: string}
              - {label: 'Youtube', name: 'youtube', widget: string}
          - label: Sections
            name: sections
            widget: object
            fields:
              - {label: 'Projects', name: 'projects', widget: boolean}
              - {label: 'Experience', name: 'experience', widget: boolean}
              - {label: 'Education', name: 'education', widget: boolean}
              - {label: 'Extra', name: 'extra', widget: boolean}
      - label: "About section"
        name: "about"
        file: "content/about.md"
        fields:
          - {label: 'Description', name: 'description', widget: string}
          - {label: 'Skill_1', name: 'skill_1', widget: string}
          - {label: 'Skill_2', name: 'skill_2', widget: string}
          - {label: 'Picture', name: 'picture', widget: image}
  - name: 'projects'
    label: 'Projects'
    folder: 'content/projects'
    format: 'frontmatter'
    create: true
    slug: '{{slug}}'
    editor:
      preview: false
    fields:
      - { label: 'Name', name: 'name', widget: 'string' }
      - { label: 'Link', name: 'link', widget: 'string' }
      - { label: 'Highlight', name: 'highlight', widget: 'string' }
      - { label: 'Description', name: 'description', widget: 'string' }
  - name: 'education'
    label: 'Education'
    folder: 'content/education'
    format: 'frontmatter'
    create: true
    slug: '{{slug}}'
    editor:
      preview: false
    fields:
      - { label: 'Name', name: 'name', widget: 'string' }
      - { label: 'Degree', name: 'degree', widget: 'string' }
      - { label: 'Highlight', name: 'highlight', widget: 'string' }
      - { label: 'Description', name: 'description', widget: 'string' }
      - { label: 'Period', name: 'period', widget: 'string' }
  - name: 'experience'
    label: 'Experience'
    folder: 'content/experience'
    format: 'frontmatter'
    create: true
    slug: '{{slug}}'
    editor:
      preview: false
    fields:
      - { label: 'Company', name: 'company', widget: 'string' }
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Highlight', name: 'highlight', widget: 'string' }
      - { label: 'Description', name: 'description', widget: 'string' }
      - { label: 'Period', name: 'period', widget: 'string' }
      - { label: 'Website', name: 'website', widget: 'string' }
  - label: 'Extra'
    name: 'Extra'
    files:
      - label: 'Extra'
        name: 'extra'
        file: 'content/extra.md'
        fields:
          - {label: 'Body', name: 'body', widget: markdown}